sudo: false
language: scala
scala:
- 2.12.10
jdk:
- openjdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
notifications:
  email: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M test scripted
